### ISSUE TITLE
get rid of meteor bcrypt warning

### ISSUE THREAD

**Issue by gotjoshua** [gibelium/meteor-react-antd-casl#2]
meteor remove accounts-password
meteor remove npm-bcrypt
yarn remove bcrypt
yarn add bcrypt
meteor add accounts-password

OR (as a reference for those who may use npm)

meteor remove accounts-password
meteor remove npm-bcrypt
meteor npm uninstall --save bcrypt
meteor npm install --save bcrypt
meteor add accounts-password

sequence of commands adapted from [this meteor discussion thread].(https://forums.meteor.com/t/npm-bcrypt-and-meteor-npm-bcrypt-madness/28714/52).

Say goodbye to this boring error message on each rebuild:
```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run
  meteor npm install --save bcrypt
in the root directory of your application.
```

**Comment by gibelium** [comment]
Coolio. Thanks for that information. Has been bugging me for a long time.
